### ISSUE TITLE
在vue3中只有click时间会被监听到

### ISSUE THREAD

**Issue by wssnail** [vulcangz/svelte-webcomponent-in-react-vue#2]
在vue3中只有click时间会被监听到，customOnClick无法触发调用vue中的方法

**Comment by vulcangz** [comment]
在 Vue 3 中要设置 [跳过组件解析](https://cn.vuejs.org/guide/extras/web-components.html#skipping-component-resolution) 才能将这个 <my-counter> 视为自定义元素。

如果把 Vue 3 包也加入到这个 monorepo，bolt 就不适用了。稍晚点我把包含 Vue 3 包的代码传到一个新的 lerna 分支。

**Comment by vulcangz** [comment]
@wssnail 这个问题已经解决了。请参考[最新提交](https://github.com/vulcangz/svelte-webcomponent-in-react-vue/commit/3caeb604a8a11f365138e3b4c65cd7a49bfa75f6) 。我将关闭这个issue。
